task_name: 'Chef-v0'
render: False
log_path: '/home/yi/project_ghent/chef/logs/'  # the root of tensorboard logging path
model_path: './models/'
alg: 'PPO'  # the algorithm used
normalization_range: [-1, 1]
xml_path: '/gymnasium_envs/robot_env_description/'  # root of the xml file
xml_file_name: 'scene_reach.xml'  # xml file for training in mujoco
basic_skill_name: ['pick', 'release']  # basic skill, fixed
specified_skill_name: ['reach', 'flip', 'pour']  # specified skills for cooking/kitchen
kitchen_tasks_name: ['flip_bottle', 'pour_water', 'pick_cube']
kitchen_tasks_chain: {'flip_bottle':['reach', 'pick', 'reach', 'flip', 'reach', 'release'],
                      'pour_water': ['reach', 'pick', 'reach', 'pour', 'reach', 'release'],
                      'pick_cube': ['reach', 'pick', 'reach', 'release'],

}
# the chain formed by skills, mainly used in robot part for DMPs
demonstration_trajectories_paths: ''  # loading demonstration trajectory for different skills
demonstration_length: 2000  # the length of the demonstration, uniformed
DMPs_weights_num: 100
max_step_one_episode: 2000
ratio_demonstration2action: 3 # the ratio between the length of demonstration and length of the action step echo epoch
# robot config
ee_pos_limitation_low: [-0.2, 0.1, 0.2]
ee_pos_limitation_high: [0.2, 0.7, 0.8]
ee_rot_limitation_low: [-180, -10, -30]
ee_rot_limitation_high: [-45, 10, 30]


